### ISSUE TITLE
harpSpatial install problem

### ISSUE THREAD

**Issue by roman7011** [harphub/harpSpatial#3]
Hi,
when trying to install harpSpatial we get an error:

$ Rscript -e 'remotes::install_github("harphub/harpSpatial")'
Downloading GitHub repo harphub/harpSpatial@master
**Error: Failed to install 'harpSpatial' from GitHub:
  Missing commas separating Remotes: 'harphub/meteogrid
  harphub/harpIO'
Execution halted**

I propose to replace file "DESCRIPTION" with the one I attach:

[DESCRIPTION.zip](https://github.com/harphub/harpSpatial/files/4925031/DESCRIPTION.zip)

Best regards
Roman Zehnal

**Comment by andrew-MET** [comment]
@adeckmyn Can you fix the Imports as well? I notice SpatialVx isn't there, for example, which I guess will also cause problems. Also lubridate is used in a couple of places as well.
