### ISSUE TITLE
SpatialVx dependency

### ISSUE THREAD

**Issue by andrew-MET** [harphub/harpSpatial#5]
I think we need to remove the SpatialVx dependency ASAP. Somewhere in the dependency tree there is a dependency on [conquer](https://cran.r-project.org/package=conquer), which requires R >= 3.6. This means that harpSpatial has the same requirement for new installations. I believe there is already a plan to remove the dependency on SpatialVx, so I think we need to put this into action as soon as we can.

**Comment by adeckmyn** [comment]
Done. Currently only FSS is re-implemented in Rcpp. Other "fuzzy" scores will follow.

**Comment by andrew-MET** [comment]
Resolvedin #6
